### ISSUE TITLE
How to have the GPU Usage on %

### ISSUE THREAD

**Issue by Impre-visible** [nickbabcock/OhmGraphite#233]
I use InfluxDB, and i want to know how to have the GPU Usage, i can have the CPU usage in % but for the GPU its not that
Please

**Comment by nickbabcock** [comment]
See if the [latest GUI build](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/suites/3066852265/artifacts/69843496) has the GPU. If it doesn't then you may want to see if you can upgrade your GPU drivers as there was a recent time where no one was able to see GPU data due to a faulty nvidia update.

**Comment by nickbabcock** [comment]
Closing for staleness.
